name: Install Dependencies for predict_python_backend

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app-service:
        description: 'Azure App Service to install dependencies for'
        required: true
        default: 'Predict-python-backend'  # Updated to use the correct Azure App Service name

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      # Step 2: Check out repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 3: Create and start virtual environment, then install dependencies
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r site/wwwroot/requirements.txt  # Adjust path if necessary
