name: Install Dependencies for predict-python-app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app-service:
        description: 'Azure App Service to install dependencies for'
        required: true
        default: 'predict-python-app'  # Default value, replace with your Azure App Service name

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      # Step 2: Check out repository (optional, depending on your setup)
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          cd site/wwwroot  # Navigate to the directory where requirements.txt is located
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Optional Steps:
      # You can add additional steps here as needed for your deployment or configuration
