name: Install Dependencies for predict-python-app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app-service:
        description: 'Azure App Service to install dependencies for'
        required: true
        default: 'predict-python-app'  # Default value, replace with your Azure App Service name

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      # Step 2: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust path if necessary

      # Step 3: Log in to Azure (Optional if Azure CLI is required)
      #- name: Azure Login
      #  uses: azure/login@v1
      #  with:
      #    creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Configure Azure App Service Application Settings (Optional)
      #- name: Configure Azure App Service Application Settings
      #  run: |
      #    az webapp config appsettings set --name ${{ github.event.inputs.app-service }} --resource-group your-resource-group --settings WEBSITE_RUN_FROM_PACKAGE=1
